// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phchmfgvvrynvdqnvbkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoY2htZmd2dnJ5bnZkcW52YmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjkxMzgsImV4cCI6MjA2MDE0NTEzOH0.0Ze7PJoR-I025evZQt8olHRQb5VHmNxMsgHmeqkKh1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);